name: tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - '*'
      - '!badges'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        qt-backend: ["pyqt5", "pyqt6", "pyside6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"
        id: extract_branch

      - name: Checkout the repo
        uses: actions/checkout@v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt update
            sudo apt install -y xvfb mesa-utils libopengl0 yaru-theme-icon libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
            libxcb-keysyms1 libxcb-cursor0 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils \
            libx11-xcb1 libxrender1 libxext6 libxi6 libxrandr2 libxinerama1 libsm6 libegl1 libgl1-mesa-dri libglx-mesa0 \
            libglu1-mesa libfontconfig1 libfreetype6 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcomposite1 libxcursor1 \
            libxdamage1 libxtst6
          fi
          python -m pip install --upgrade pip
          pip install matplotlib flake8 pytest pytest-cov pytest-qt pytest-xvfb setuptools wheel numpy h5py ${{ matrix.qt-backend }}
          pip install -e .

      - name: Create local pymodaq folder setup env (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo mkdir -p /etc/.pymodaq
          sudo chmod uo+rw /etc/.pymodaq

      - name: Linting with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=docs

      - name: Tests with ${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.qt-backend }}
        id: tests
        shell: bash
        run: |
          mkdir coverage
          if [ "${{ runner.os }}" == "Linux" ]; then
            export QT_DEBUG_PLUGINS=1
            export QT_OPENGL=software
            export QT_QPA_PLATFORM=offscreen
            export LIBGL_ALWAYS_SOFTWARE=1
            export MESA_LOADER_DRIVER_OVERRIDE=softpipe
            xvfb-run -a python -m pytest -vv --cov=pymodaq_gui
          else
            set DEBUG_PLUGINS=1
            set OPENGL=software
            set QPA_PLATFORM=offscreen
            set GL_ALWAYS_SOFTWARE=1
            set A_LOADER_DRIVER_OVERRIDE=softpipe
            
            pytest -vv --cov=pymodaq_gui
          fi
          mv .coverage coverage/coverage_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.qt-backend }}


      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}_${{ matrix.qt-backend }}
          path: coverage/coverage_${{ matrix.os }}_${{ matrix.python-version }}_${{ matrix.qt-backend }}

      # Badge generation steps remain unchanged
      - name: Create destination directory
        if: ${{ always() }}
        run: mkdir -p "${{ steps.extract_branch.outputs.branch }}"

      - name: generate badge (success)
        if: ${{ success() }}
        uses: emibcn/badge-action@v2.0.3
        with:
          label: ''
          status: 'passing'
          color: 'green'
          path: '${{ steps.extract_branch.outputs.branch }}/tests_${{runner.os}}_${{matrix.python-version}}_${{matrix.qt-backend}}.svg'

      - name: generate badge (fail)
        if: ${{ failure() }}
        uses: emibcn/badge-action@v2.0.3
        with:
          label: ''
          status: 'failing'
          color: 'red'
          path: '${{ steps.extract_branch.outputs.branch }}/tests_${{runner.os}}_${{matrix.python-version}}_${{matrix.qt-backend}}.svg'

      - name: Upload badge artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name:  tests_${{runner.os}}_${{matrix.python-version}}_${{matrix.qt-backend}}
          path: '${{ steps.extract_branch.outputs.branch }}/tests_${{runner.os}}_${{matrix.python-version}}_${{matrix.qt-backend}}.svg'
          if-no-files-found: error
